// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from 'D:/study/study_2/CC/twoC/node_modules/@ant-design/icons/es/icons/SmileOutlined';
export default { SmileOutlined };
