// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from 'D:/forWorks/外包/双碳系统/system/node_modules/@ant-design/icons/es/icons/SmileOutlined';
export default { SmileOutlined };
